![data-x](http://oi64.tinypic.com/o858n4.jpg)






# Homework 02

## Numpy Introduction


__1a) Create two numpy arrays (a and b). a should be all integers between 10-19 (inclusive), and b should be ten evenly spaced numbers between 1-7. Print all the results below:__ 


i) Square all the elements in both arrays (element-wise)  
ii)  Add both the squared arrays (e.g., [1,2] + [3,4] = [4,6])  
iii)  Sum the elements with even indices of the added array.  
iv)  Take the square root of the added array (element-wise square root)__


In [25]:
import numpy as np

a = np.array(np.arange(10,20))
b = np.array(np.linspace(1,7,10))

a_2 = a**2
b_2 = b**2
ab2_sum = a_2 + b_2

# i
print(a_2, b_2)
# ii
print(ab2_sum)
# iii
print(np.sum(ab2_sum[::2]))
# iv
print(np.sqrt(ab2_sum))

[100 121 144 169 196 225 256 289 324 361] [  1.           2.77777778   5.44444444   9.          13.44444444
  18.77777778  25.          32.11111111  40.11111111  49.        ]
[ 101.          123.77777778  149.44444444  178.          209.44444444
  243.77777778  281.          321.11111111  364.11111111  410.        ]
1105.0
[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]


__1b) Append b to a, reshape the appended array so that it is a 5x4, 2d array and store the results in a variable called m. Print m.__


In [29]:
m = np.append(a,b).reshape(5,4)
print(m)

array([[ 10.        ,  11.        ,  12.        ,  13.        ],
       [ 14.        ,  15.        ,  16.        ,  17.        ],
       [ 18.        ,  19.        ,   1.        ,   1.66666667],
       [  2.33333333,   3.        ,   3.66666667,   4.33333333],
       [  5.        ,   5.66666667,   6.33333333,   7.        ]])

__1c) Extract the second and the third column of the m matrix. Store the resulting 5x2 matrix in a new variable called m2. Print m2.__


In [36]:
m2 = m[:,1:3]
print(m2)

[[ 11.          12.        ]
 [ 15.          16.        ]
 [ 19.           1.        ]
 [  3.           3.66666667]
 [  5.66666667   6.33333333]]


__1d) Take the dot product of m2 and m store the results in a matrix called m3. Print m3.
Note that Dot product of two matrices A.B =A<sup>T</sup>B__

In [41]:
m3 = np.dot(m2.T, m)
print(m3)

[[ 697.33333333  748.11111111  437.88888889  482.33333333]
 [ 402.22222222  437.88888889  454.55555556  489.88888889]]


__1e) Round the m3 matrix to two decimal points. Store the result in place and print the new m3.__


In [48]:
m3= np.round(m3,decimals=2)
print(m3)

[[ 697.33  748.11  437.89  482.33]
 [ 402.22  437.89  454.56  489.89]]


__1f) Sort the m3 array so that the highest value is at the top left, the next highest value to the right of the highest, and the lowest value is at the bottom right. Print the sorted m3 array.__


In [56]:
m3 = np.sort(m3.ravel()).reshape(2,4)
print(m3)

[[ 402.22  437.89  437.89  454.56]
 [ 482.33  489.89  697.33  748.11]]


## NumPy and Masks
__2a) create an array called 'f' where the values are sin(x) for x from 0 to pi with 100 values in f__
* print f
* use a 'mask' and print an array that is True when f >= 1/2 and False when f < 1/2
* create and print an array sequence that has only those values where f>= 1/2



In [87]:
f = np.sin(np.linspace(0,np.pi,10))
print(f>=.5)
print(f[f>=.5])

[False False  True  True  True  True  True  True False False]
[ 0.64278761  0.8660254   0.98480775  0.98480775  0.8660254   0.64278761]


## NumPy and 2 Variable Prediction

__ Let 'x' be the number of miles a person drives per day and 'y' be the dollars spent on buying car fuel (per day).__
  
__We have created 2 numpy arrays each of size 100 that represent x and y.  
x ( number of miles) ranges from 1 to 10 with a uniform noise of (0,1/2)  
y (money spent in dollars) will be from 1 to 20 with a uniform noise (0,1)__ 


In [90]:
# seed the random number generator with a fixed value
import numpy as np
np.random.seed(500)

x=np.linspace(1,10,100)+ np.random.uniform(low=0,high=.5,size=100) 
y=np.linspace(1,20,100)+ np.random.uniform(low=0,high=1,size=100)
print ('x = ',x)
print ('y= ',y)

x =  [  1.34683976   1.12176759   1.51512398   1.55233174   1.40619168
   1.65075498   1.79399331   1.80243817   1.89844195   2.00100023
   2.3344038    2.22424872   2.24914511   2.36268477   2.49808849
   2.8212704    2.68452475   2.68229427   3.09511169   2.95703884
   3.09047742   3.2544361    3.41541904   3.40886375   3.50672677
   3.74960644   3.64861355   3.7721462    3.56368566   4.01092701
   4.15630694   4.06088549   4.02517179   4.25169402   4.15897504
   4.26835333   4.32520644   4.48563164   4.78490721   4.84614839
   4.96698768   5.18754259   5.29582013   5.32097781   5.0674106
   5.47601124   5.46852704   5.64537452   5.49642807   5.89755027
   5.68548923   5.76276141   5.94613234   6.18135713   5.96522091
   6.0275473    6.54290191   6.4991329    6.74003765   6.81809807
   6.50611821   6.91538752   7.01250925   6.89905417   7.31314433
   7.20472297   7.1043621    7.48199528   7.58957227   7.61744354
   7.6991707    7.85436822   8.03510784   7.80787781   8.22410224
   7.9

__3a) Find Expected value of x and the expected value of y__

In [92]:
print(np.mean(x))
print(np.mean(y))

5.78253254159
11.0129816833


__3b) Find variance of distributions of  x and  y__

In [100]:
print(np.var(x))
print(np.var(y))

7.03332752948
30.1139035755


__3c) Find co-variance of x and y.__

In [101]:
print(np.cov(x,y)[0,1])

14.6577438328


__3d) Assuming that number of dollars spent in car fuel is only dependant on the miles driven, by  a linear relationship.  
Write code that uses a linear predictor to calculate a predicted value of y for each x
ie y_predicted = f(x) = y0+mx.__  

In [105]:
y_0 = np.mean(y) - np.cov(x,y)[0,1]/np.var(x)*np.mean(x)
m = np.cov(x,y)[0,1]/np.var(x)
y_predicted = y_0 + m*x
print(y_predicted)

[  1.76881551   1.29975583   2.11952674   2.19706924   1.89250733
   2.40218732   2.70070189   2.71830133   2.91837716   3.13211283
   3.82693958   3.59737186   3.64925696   3.88587827   4.16806519
   4.84158958   4.55660602   4.55195763   5.41228611   5.1245366
   5.4026281    5.74432472   6.07981979   6.06615829   6.27010885
   6.77628008   6.56580674   6.82325387   6.38881354   7.3208829
   7.62386066   7.42499842   7.35056961   7.82265125   7.62942107
   7.85736994   7.97585416   8.31018686   8.93388945   9.0615186
   9.31335266   9.77299816   9.998653    10.05108265   9.52263814
  10.37417868  10.3585813   10.72713873  10.41672819  11.25268336
  10.81073943  10.97177784  11.35393039  11.84414852  11.39371175
  11.52360252  12.59762273  12.50640631  13.00846171  13.17114283
  12.52096398  13.37389806  13.57630372  13.33985868  14.2028396
  13.97688504  13.76772884  14.55473193  14.7789268   14.83701167
  15.00733442  15.33077245  15.70744125  15.23388452  16.10131336
  15.6210674  

__3e) Predict y for each value in x, pur the error into an array called y_error__

In [107]:
print(y_predicted)

[  1.76881551   1.29975583   2.11952674   2.19706924   1.89250733
   2.40218732   2.70070189   2.71830133   2.91837716   3.13211283
   3.82693958   3.59737186   3.64925696   3.88587827   4.16806519
   4.84158958   4.55660602   4.55195763   5.41228611   5.1245366
   5.4026281    5.74432472   6.07981979   6.06615829   6.27010885
   6.77628008   6.56580674   6.82325387   6.38881354   7.3208829
   7.62386066   7.42499842   7.35056961   7.82265125   7.62942107
   7.85736994   7.97585416   8.31018686   8.93388945   9.0615186
   9.31335266   9.77299816   9.998653    10.05108265   9.52263814
  10.37417868  10.3585813   10.72713873  10.41672819  11.25268336
  10.81073943  10.97177784  11.35393039  11.84414852  11.39371175
  11.52360252  12.59762273  12.50640631  13.00846171  13.17114283
  12.52096398  13.37389806  13.57630372  13.33985868  14.2028396
  13.97688504  13.76772884  14.55473193  14.7789268   14.83701167
  15.00733442  15.33077245  15.70744125  15.23388452  16.10131336
  15.6210674  

In [109]:
error = y - y_predicted
print(error)

[ -1.05314309e-01   7.21703366e-01  -1.13662110e-02   6.30957167e-02
   7.03682516e-02   5.53276173e-01   3.28116980e-01   6.17351628e-01
  -1.63719369e-01   2.92897867e-01  -4.30238098e-01  -2.03594191e-01
   1.35776473e-01   4.97052216e-01   1.61570667e-01  -8.02339188e-01
   1.80312658e-01  -2.50973643e-01  -5.70653214e-01  -3.42777034e-01
  -4.04970232e-01  -4.26856544e-01  -3.11373081e-01  -1.28920801e-01
  -5.41992427e-01  -6.65439261e-02   1.15626927e-01  -2.48426563e-01
   7.88562495e-01   2.27749619e-01  -3.21646464e-01  -1.04741121e-01
   4.29669229e-01   8.86824064e-02   6.47120628e-01   8.34662873e-01
   8.06344483e-01   1.48788597e-01  -4.29423037e-02  -2.44319388e-01
  -4.42282956e-01  -1.11072540e-01  -5.96590507e-01  -1.91174825e-01
   8.09596391e-02  -3.00316025e-01   3.37218195e-01  -5.99195710e-02
   7.65834652e-01  -6.78364995e-01   6.56707732e-01  -2.77886742e-02
  -8.94778085e-02   2.53399759e-01   7.26168620e-01   5.97954474e-01
  -4.21485798e-01  -6.89043727e-02

__3f) Write code that calculates the root mean square error(RMSE), that is root of average of y-error squared__

In [113]:
RMSE = np.sqrt(np.mean(error**2))
print(RMSE)

0.421318661997
